#!/usr/bin/env python3
"""Extract the inline SteamNetworkingIPAddr/SteamNetworkingIdentity method bodies from
Proton's copy of steamnetworkingtypes.h (where they sit in an '#if 0' block and the
unions are named 'data') so steam_api_helpers.cpp can compile them."""
import re, sys

src, dst = sys.argv[1], sys.argv[2]
lines = open(src, encoding='latin-1').read().split('\n')
start = next(i for i, l in enumerate(lines) if l.startswith('inline void SteamNetworkingIPAddr::Clear()'))
end = next(i for i, l in enumerate(lines) if 'SteamNetworkingIdentity::operator==' in l)
body = '\n'.join(lines[start:end + 1])
body = body.replace('const void *data, size_t cbLen', 'const void *pData, size_t cbLen')
body = body.replace('memcpy( m_genericBytes, data,', 'memcpy( m_genericBytes, pData,')
body = re.sub(r'(?<![.\w])(m_ipv6|m_ipv4|m_steamID64|m_PSNID|m_szGenericString|m_szXboxPairwiseID|m_genericBytes|m_ip)\b',
              r'data.\1', body)
body = body.replace('x.m_genericBytes', 'x.data.m_genericBytes')
open(dst, 'w').write('/* Generated by gen_sdk_inline.py from Proton\'s steamnetworkingtypes.h. */\n' + body + '\n')
