#!/usr/bin/env python3
"""Generate Windows ARM64 winhttp proxy stubs for BSIPA's Doorstop.

Doorstop's proxy.c relies on MSVC turning 'return originalFunctions[i]();' into a bare
jump. On ARM64 we emit the jump explicitly (adrp/add/ldr/br x16), so no argument
register is touched.

usage: gen_proxy_arm64.py <Doorstop/Proxy/proxy.c> <out.c>
"""
import re
import sys

src = open(sys.argv[1]).read()
funcs = re.findall(r'^ADD_ORIGINAL\((\d+), (\w+)\);', src, re.M)
out = ['/* Generated by gen_proxy_arm64.py from Doorstop/Proxy/proxy.c. */', '#include <windows.h>', '',
       f'FARPROC originalFunctions[{len(funcs)}] = {{0}};', '', 'void loadFunctions(HMODULE dll)', '{']
out += [f'\toriginalFunctions[{i}] = GetProcAddress(dll, "{name}");' for i, name in funcs]
out += ['}', '']
for i, name in funcs:
    out.append(f'__asm__(".globl {name}\\n.def {name}; .scl 2; .type 32; .endef\\n{name}:\\n'
               f'\\tadrp x16, originalFunctions\\n\\tadd x16, x16, :lo12:originalFunctions\\n'
               f'\\tldr x16, [x16, #{int(i) * 8}]\\n\\tbr x16\\n");')
open(sys.argv[2], 'w').write('\n'.join(out) + '\n')
